# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SLD4raster
                                 A QGIS plugin
 Generates SLD (Styled Layer Descriptor) for raster layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-15
        copyright            : (C) 2018 by Mehmet Selim BILGIN
        email                : mselimbilgin@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SLD4raster class from file SLD4raster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sld4raster import SLD4raster
    return SLD4raster(iface)
