# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SLD4rasterDialog
                                 A QGIS plugin
 Generates SLD (Styled Layer Descriptor) for raster layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-15
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Mehmet Selim BILGIN
        email                : mselimbilgin@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic
from PyQt5 import QtWidgets

FORM_CLASS_MAIN, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'sld4raster_dialog_base.ui'))
	
FORM_CLASS_UPLOAD, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geoserver_upload.ui'))	


class SLD4rasterDialog(QtWidgets.QDialog, FORM_CLASS_MAIN):
    def __init__(self, parent=None):
        """Constructor."""
        super(SLD4rasterDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
		
class GeoserverUploadDialog(QtWidgets.QDialog, FORM_CLASS_UPLOAD):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeoserverUploadDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
